resolver: lts-19.28
packages:
- .
ghc-options:
  "$locals":
    -Wall -Wcompat -Werror -Widentities
    -Wincomplete-record-updates -Wincomplete-uni-patterns
    -Wmissing-home-modules -Wmissing-export-lists -Wpartial-fields
    -Wredundant-constraints -Wunused-packages -Wmissing-deriving-strategies
    -Wno-unticked-promoted-constructors
extra-deps:
- env-guard-0.2@sha256:59410eed9b9ddbd115760a59c7170927320d8612e414701d323a0c8985c97523,1251
- git: https://github.com/tbidne/algebra-simple.git
  commit: 62a744d82255d7acb6b84cd3bb5e324a9ad36486
nix:
  shell-file: nix/stack.nix
